/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author rpa06
 */
public class LibraryMain extends javax.swing.JFrame {

    /**
     * Creates new form LibraryMain
     */
    static String USER;

    public LibraryMain(String userName) {
        initComponents();

        USER = userName;
        jLabelWelcomeUser.setText("Welcome " + USER);
        jPanelReserveBook.setVisible(false);
        jPanelRequestedBookList.setVisible(false);
        jPanelPendingReturn.setVisible(false);
        jPanelHsitory.setVisible(false);
        jPanelFeedback.setVisible(false);
        jPanelSettings.setVisible(false);
        clock();

    }

    //this method call for show and hide toggle panels when button click
    private void togglePanels(String buttonName) {
        switch (buttonName) {
            case "ReserveBook":
                jPanelReserveBook.setVisible(true);
                jPanelRequestedBookList.setVisible(false);
                jPanelPendingReturn.setVisible(false);
                jPanelHsitory.setVisible(false);
                jPanelFeedback.setVisible(false);
                jPanelSettings.setVisible(false);
                break;
            case "RequestedList":
                jPanelReserveBook.setVisible(false);
                jPanelRequestedBookList.setVisible(true);
                jPanelPendingReturn.setVisible(false);
                jPanelHsitory.setVisible(false);
                jPanelFeedback.setVisible(false);
                jPanelSettings.setVisible(false);
                break;
            case "PendingBooks":
                jPanelReserveBook.setVisible(false);
                jPanelRequestedBookList.setVisible(false);
                jPanelPendingReturn.setVisible(true);
                jPanelHsitory.setVisible(false);
                jPanelFeedback.setVisible(false);
                jPanelSettings.setVisible(false);
                break;
            case "History":
                jPanelReserveBook.setVisible(false);
                jPanelRequestedBookList.setVisible(false);
                jPanelPendingReturn.setVisible(false);
                jPanelHsitory.setVisible(true);
                jPanelFeedback.setVisible(false);
                jPanelSettings.setVisible(false);
                break;
            case "Feedbacks":
                jPanelReserveBook.setVisible(false);
                jPanelRequestedBookList.setVisible(false);
                jPanelPendingReturn.setVisible(false);
                jPanelHsitory.setVisible(false);
                jPanelFeedback.setVisible(true);
                jPanelSettings.setVisible(false);
                break;
            case "Settings":
                jPanelReserveBook.setVisible(false);
                jPanelRequestedBookList.setVisible(false);
                jPanelPendingReturn.setVisible(false);
                jPanelHsitory.setVisible(false);
                jPanelFeedback.setVisible(false);
                jPanelSettings.setVisible(true);
                break;

            default:
                break;
        }
    }

    public void clock() {
        Thread clock = new Thread() {
            public void run() {
                try {
                    for (;;) {
                        Calendar cal = new GregorianCalendar();
                        jLableTime.setText(cal.get(Calendar.HOUR) + ":" + cal.get(Calendar.MINUTE) + ":" + cal.get(Calendar.SECOND) + " / " + cal.get(Calendar.YEAR) + "-" + cal.get(Calendar.MONTH) + "-" + cal.get(Calendar.DATE));
                        sleep(1000);
                    }
                } catch (Exception e) {

                }
            }
        };
        clock.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneLibraryMain = new javax.swing.JDesktopPane();
        jPanelHeader = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelWelcomeUser = new javax.swing.JLabel();
        jLableTime = new javax.swing.JLabel();
        jPanelButtons = new javax.swing.JPanel();
        jButtonReserveBook = new javax.swing.JButton();
        jButtonRequestedBookList = new javax.swing.JButton();
        jButtonPendingReturn = new javax.swing.JButton();
        jButtonHistory = new javax.swing.JButton();
        jButtonFeedback = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jButtonSettings = new javax.swing.JButton();
        jPanelToggle = new javax.swing.JPanel();
        jPanelReserveBook = new javax.swing.JPanel();
        jTabbedPaneReserveBook = new javax.swing.JTabbedPane();
        jPanelSearchBookTab = new javax.swing.JPanel();
        jTextFieldBookName = new javax.swing.JTextField();
        jTextFieldISBN1 = new javax.swing.JTextField();
        jTextFieldBookName1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonSearchBook = new javax.swing.JButton();
        jButtonSearchBook1 = new javax.swing.JButton();
        jPanelReserveBookTab = new javax.swing.JPanel();
        jTextFieldBookId = new javax.swing.JTextField();
        jTextFieldAvailability = new javax.swing.JTextField();
        jTextFieldReserveISBN = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jTextFieldAuthor = new javax.swing.JTextField();
        jTextFieldReserveBookName = new javax.swing.JTextField();
        jButtonConfirmReservation = new javax.swing.JButton();
        jPanelRequestedBookList = new javax.swing.JPanel();
        jTabbedPaneRequestedList = new javax.swing.JTabbedPane();
        jPanelRequestedList = new javax.swing.JPanel();
        jTextFieldISBN2 = new javax.swing.JTextField();
        jTextFieldBookName3 = new javax.swing.JTextField();
        jTextFieldBookName2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButtonCancelRequest = new javax.swing.JButton();
        jPanelPendingReturn = new javax.swing.JPanel();
        jTabbedPanePendingReturn = new javax.swing.JTabbedPane();
        jPanelPending = new javax.swing.JPanel();
        jTextFieldISBN3 = new javax.swing.JTextField();
        jTextFieldBookName4 = new javax.swing.JTextField();
        jTextFieldBookName5 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButtonCancelRequest1 = new javax.swing.JButton();
        jPanelHsitory = new javax.swing.JPanel();
        jTabbedPanelHistory = new javax.swing.JTabbedPane();
        jPanelHistory = new javax.swing.JPanel();
        jTextFieldISBN4 = new javax.swing.JTextField();
        jTextFieldBookName6 = new javax.swing.JTextField();
        jTextFieldBookName7 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButtonCancelRequest2 = new javax.swing.JButton();
        jPanelFeedback = new javax.swing.JPanel();
        jTabbedPanelFeedback = new javax.swing.JTabbedPane();
        jPanelFeedback1 = new javax.swing.JPanel();
        jTextFieldISBN5 = new javax.swing.JTextField();
        jTextFieldBookName8 = new javax.swing.JTextField();
        jTextFieldBookName9 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButtonCancelRequest3 = new javax.swing.JButton();
        jPanelSubmitFeedback = new javax.swing.JPanel();
        jTextFieldBookId1 = new javax.swing.JTextField();
        jTextFieldAvailability1 = new javax.swing.JTextField();
        jTextFieldReserveISBN1 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaDescription1 = new javax.swing.JTextArea();
        jTextFieldAuthor1 = new javax.swing.JTextField();
        jTextFieldReserveBookName1 = new javax.swing.JTextField();
        jButtonConfirmReservation1 = new javax.swing.JButton();
        jPanelSettings = new javax.swing.JPanel();
        jTabbedPanelHistory1 = new javax.swing.JTabbedPane();
        jPanelEditProfile = new javax.swing.JPanel();
        jTextFieldISBN6 = new javax.swing.JTextField();
        jTextFieldBookName10 = new javax.swing.JTextField();
        jTextFieldBookName11 = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jButtonCancelRequest4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System : Member");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPaneLibraryMain.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPaneLibraryMain.setForeground(new java.awt.Color(255, 255, 255));
        jDesktopPaneLibraryMain.setPreferredSize(new java.awt.Dimension(1022, 710));
        jDesktopPaneLibraryMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHeader.setBackground(new java.awt.Color(0, 102, 102));
        jPanelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setIcon(new javax.swing.ImageIcon("C:\\SLIIT\\LibraryManagementSystem\\src\\View\\Images\\librarylogo.png")); // NOI18N
        jPanelHeader.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabelWelcomeUser.setForeground(new java.awt.Color(204, 204, 204));
        jLabelWelcomeUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanelHeader.add(jLabelWelcomeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 10, 290, 20));

        jLableTime.setForeground(new java.awt.Color(204, 204, 204));
        jLableTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanelHeader.add(jLableTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 94, 150, 20));

        jDesktopPaneLibraryMain.add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1022, 120));

        jPanelButtons.setBackground(new java.awt.Color(0, 102, 102));
        jPanelButtons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonReserveBook.setBackground(new java.awt.Color(0, 102, 102));
        jButtonReserveBook.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jButtonReserveBook.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReserveBook.setIcon(new javax.swing.ImageIcon("C:\\SLIIT\\LibraryManagementSystem\\src\\View\\Images\\menuBtn.png")); // NOI18N
        jButtonReserveBook.setText("RESERVE BOOK");
        jButtonReserveBook.setFocusPainted(false);
        jButtonReserveBook.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonReserveBook.setIconTextGap(5);
        jButtonReserveBook.setMargin(new java.awt.Insets(2, 0, 2, 5));
        jButtonReserveBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonReserveBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonReserveBookMouseExited(evt);
            }
        });
        jButtonReserveBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReserveBookActionPerformed(evt);
            }
        });
        jPanelButtons.add(jButtonReserveBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 40));

        jButtonRequestedBookList.setBackground(new java.awt.Color(0, 102, 102));
        jButtonRequestedBookList.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jButtonRequestedBookList.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRequestedBookList.setIcon(new javax.swing.ImageIcon("C:\\SLIIT\\LibraryManagementSystem\\src\\View\\Images\\menuBtn.png")); // NOI18N
        jButtonRequestedBookList.setText("REQUESTED LIST");
        jButtonRequestedBookList.setFocusPainted(false);
        jButtonRequestedBookList.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonRequestedBookList.setIconTextGap(5);
        jButtonRequestedBookList.setMargin(new java.awt.Insets(2, 0, 2, 5));
        jButtonRequestedBookList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRequestedBookListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRequestedBookListMouseExited(evt);
            }
        });
        jButtonRequestedBookList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRequestedBookListActionPerformed(evt);
            }
        });
        jPanelButtons.add(jButtonRequestedBookList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 190, 40));

        jButtonPendingReturn.setBackground(new java.awt.Color(0, 102, 102));
        jButtonPendingReturn.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jButtonPendingReturn.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPendingReturn.setIcon(new javax.swing.ImageIcon("C:\\SLIIT\\LibraryManagementSystem\\src\\View\\Images\\menuBtn.png")); // NOI18N
        jButtonPendingReturn.setText("PENDING BOOKS");
        jButtonPendingReturn.setFocusPainted(false);
        jButtonPendingReturn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonPendingReturn.setIconTextGap(5);
        jButtonPendingReturn.setMargin(new java.awt.Insets(2, 0, 2, 5));
        jButtonPendingReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonPendingReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonPendingReturnMouseExited(evt);
            }
        });
        jButtonPendingReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPendingReturnActionPerformed(evt);
            }
        });
        jPanelButtons.add(jButtonPendingReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 190, 40));

        jButtonHistory.setBackground(new java.awt.Color(0, 102, 102));
        jButtonHistory.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jButtonHistory.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHistory.setIcon(new javax.swing.ImageIcon("C:\\SLIIT\\LibraryManagementSystem\\src\\View\\Images\\menuBtn.png")); // NOI18N
        jButtonHistory.setText("HISTORY");
        jButtonHistory.setFocusPainted(false);
        jButtonHistory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonHistory.setIconTextGap(5);
        jButtonHistory.setMargin(new java.awt.Insets(2, 0, 2, 5));
        jButtonHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonHistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonHistoryMouseExited(evt);
            }
        });
        jButtonHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHistoryActionPerformed(evt);
            }
        });
        jPanelButtons.add(jButtonHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 190, 40));

        jButtonFeedback.setBackground(new java.awt.Color(0, 102, 102));
        jButtonFeedback.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jButtonFeedback.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFeedback.setIcon(new javax.swing.ImageIcon("C:\\SLIIT\\LibraryManagementSystem\\src\\View\\Images\\menuBtn.png")); // NOI18N
        jButtonFeedback.setText("FEEDBACK");
        jButtonFeedback.setFocusPainted(false);
        jButtonFeedback.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonFeedback.setIconTextGap(5);
        jButtonFeedback.setMargin(new java.awt.Insets(2, 0, 2, 5));
        jButtonFeedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonFeedback11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonFeedback11MouseExited(evt);
            }
        });
        jButtonFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeedbackActionPerformed(evt);
            }
        });
        jPanelButtons.add(jButtonFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 190, 40));

        jButtonLogout.setBackground(new java.awt.Color(0, 102, 102));
        jButtonLogout.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogout.setIcon(new javax.swing.ImageIcon("C:\\SLIIT\\LibraryManagementSystem\\src\\View\\Images\\logout.png")); // NOI18N
        jButtonLogout.setText("LOGOUT");
        jButtonLogout.setFocusPainted(false);
        jButtonLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonLogout.setIconTextGap(5);
        jButtonLogout.setMargin(new java.awt.Insets(2, 0, 2, 5));
        jButtonLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLogout11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLogout11MouseExited(evt);
            }
        });
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        jPanelButtons.add(jButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 190, 40));

        jButtonSettings.setBackground(new java.awt.Color(0, 102, 102));
        jButtonSettings.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jButtonSettings.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSettings.setIcon(new javax.swing.ImageIcon("C:\\SLIIT\\LibraryManagementSystem\\src\\View\\Images\\settings.png")); // NOI18N
        jButtonSettings.setText("SETTINGS");
        jButtonSettings.setFocusPainted(false);
        jButtonSettings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonSettings.setIconTextGap(5);
        jButtonSettings.setMargin(new java.awt.Insets(2, 0, 2, 5));
        jButtonSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSettings11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSettings11MouseExited(evt);
            }
        });
        jButtonSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSettingsActionPerformed(evt);
            }
        });
        jPanelButtons.add(jButtonSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 190, 40));

        jDesktopPaneLibraryMain.add(jPanelButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 210, 570));

        jPanelToggle.setBackground(new java.awt.Color(0, 102, 102));
        jPanelToggle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelReserveBook.setBackground(new java.awt.Color(255, 255, 255));
        jPanelReserveBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPaneReserveBook.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPaneReserveBook.setFocusable(false);
        jTabbedPaneReserveBook.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanelSearchBookTab.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSearchBookTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldBookName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBookName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Author of the Book"));
        jPanelSearchBookTab.add(jTextFieldBookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 200, 40));

        jTextFieldISBN1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldISBN1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "ISBN of the Book"));
        jPanelSearchBookTab.add(jTextFieldISBN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 200, 40));

        jTextFieldBookName1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBookName1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Name of the Book"));
        jPanelSearchBookTab.add(jTextFieldBookName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 200, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanelSearchBookTab.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 750, 320));

        jButtonSearchBook.setBackground(new java.awt.Color(0, 102, 102));
        jButtonSearchBook.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSearchBook.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSearchBook.setIcon(new javax.swing.ImageIcon("C:\\SLIIT\\LibraryManagementSystem\\src\\View\\Images\\reservebtn.png")); // NOI18N
        jButtonSearchBook.setText("Reserve");
        jButtonSearchBook.setFocusable(false);
        jButtonSearchBook.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonSearchBook.setMargin(new java.awt.Insets(2, 0, 2, 5));
        jPanelSearchBookTab.add(jButtonSearchBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 100, 30));

        jButtonSearchBook1.setBackground(new java.awt.Color(0, 102, 102));
        jButtonSearchBook1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSearchBook1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSearchBook1.setIcon(new javax.swing.ImageIcon("C:\\SLIIT\\LibraryManagementSystem\\src\\View\\Images\\searchbtn.png")); // NOI18N
        jButtonSearchBook1.setText("Search");
        jButtonSearchBook1.setFocusable(false);
        jButtonSearchBook1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonSearchBook1.setMargin(new java.awt.Insets(2, 0, 2, 5));
        jPanelSearchBookTab.add(jButtonSearchBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 100, 30));

        jTabbedPaneReserveBook.addTab("Search Book", jPanelSearchBookTab);

        jPanelReserveBookTab.setBackground(new java.awt.Color(255, 255, 255));
        jPanelReserveBookTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldBookId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBookId.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Book ID"));
        jPanelReserveBookTab.add(jTextFieldBookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 40));

        jTextFieldAvailability.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldAvailability.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Availability"));
        jPanelReserveBookTab.add(jTextFieldAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 200, 40));

        jTextFieldReserveISBN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldReserveISBN.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Book ISBN"));
        jPanelReserveBookTab.add(jTextFieldReserveISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 200, 40));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Description"));

        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setRows(6);
        jScrollPane3.setViewportView(jTextAreaDescription);

        jPanelReserveBookTab.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 520, 140));

        jTextFieldAuthor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldAuthor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Author Name"));
        jPanelReserveBookTab.add(jTextFieldAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 200, 40));

        jTextFieldReserveBookName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldReserveBookName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Book Name"));
        jPanelReserveBookTab.add(jTextFieldReserveBookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 200, 40));

        jButtonConfirmReservation.setBackground(new java.awt.Color(0, 102, 102));
        jButtonConfirmReservation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonConfirmReservation.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConfirmReservation.setIcon(new javax.swing.ImageIcon("C:\\SLIIT\\LibraryManagementSystem\\src\\View\\Images\\reservebtn.png")); // NOI18N
        jButtonConfirmReservation.setText("Confirm");
        jButtonConfirmReservation.setFocusable(false);
        jButtonConfirmReservation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanelReserveBookTab.add(jButtonConfirmReservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 100, 30));

        jTabbedPaneReserveBook.addTab("Reserve Book", jPanelReserveBookTab);

        jPanelReserveBook.add(jTabbedPaneReserveBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 570));

        jPanelToggle.add(jPanelReserveBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 570));

        jPanelRequestedBookList.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRequestedBookList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPaneRequestedList.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPaneRequestedList.setFocusable(false);
        jTabbedPaneRequestedList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanelRequestedList.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRequestedList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldISBN2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldISBN2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "ISBN of the Book"));
        jPanelRequestedList.add(jTextFieldISBN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 200, 40));

        jTextFieldBookName3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBookName3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Name of the Book"));
        jPanelRequestedList.add(jTextFieldBookName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 200, 40));

        jTextFieldBookName2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBookName2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Author of the Book"));
        jPanelRequestedList.add(jTextFieldBookName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 200, 40));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanelRequestedList.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 750, 320));

        jButtonCancelRequest.setBackground(new java.awt.Color(0, 102, 102));
        jButtonCancelRequest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonCancelRequest.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelRequest.setIcon(new javax.swing.ImageIcon("C:\\SLIIT\\LibraryManagementSystem\\src\\View\\Images\\reservebtn.png")); // NOI18N
        jButtonCancelRequest.setText("Cancel Request");
        jButtonCancelRequest.setFocusable(false);
        jButtonCancelRequest.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonCancelRequest.setMargin(new java.awt.Insets(2, 0, 2, 5));
        jPanelRequestedList.add(jButtonCancelRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 120, 30));

        jTabbedPaneRequestedList.addTab("Requested Book List", jPanelRequestedList);

        jPanelRequestedBookList.add(jTabbedPaneRequestedList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 570));

        jPanelToggle.add(jPanelRequestedBookList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 570));

        jPanelPendingReturn.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPendingReturn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPanePendingReturn.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPanePendingReturn.setFocusable(false);
        jTabbedPanePendingReturn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanelPending.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPending.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldISBN3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldISBN3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "ISBN of the Book"));
        jPanelPending.add(jTextFieldISBN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 200, 40));

        jTextFieldBookName4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBookName4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Name of the Book"));
        jPanelPending.add(jTextFieldBookName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 200, 40));

        jTextFieldBookName5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBookName5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Author of the Book"));
        jPanelPending.add(jTextFieldBookName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 200, 40));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jPanelPending.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 750, 320));

        jButtonCancelRequest1.setBackground(new java.awt.Color(0, 102, 102));
        jButtonCancelRequest1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonCancelRequest1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelRequest1.setIcon(new javax.swing.ImageIcon("C:\\SLIIT\\LibraryManagementSystem\\src\\View\\Images\\reservebtn.png")); // NOI18N
        jButtonCancelRequest1.setText("Cancel Request");
        jButtonCancelRequest1.setFocusable(false);
        jButtonCancelRequest1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonCancelRequest1.setMargin(new java.awt.Insets(2, 0, 2, 5));
        jPanelPending.add(jButtonCancelRequest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 120, 30));

        jTabbedPanePendingReturn.addTab("Pending Return Book List", jPanelPending);

        jPanelPendingReturn.add(jTabbedPanePendingReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 570));

        jPanelToggle.add(jPanelPendingReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 570));

        jPanelHsitory.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHsitory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPanelHistory.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPanelHistory.setFocusable(false);
        jTabbedPanelHistory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanelHistory.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHistory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldISBN4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldISBN4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "ISBN of the Book"));
        jPanelHistory.add(jTextFieldISBN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 200, 40));

        jTextFieldBookName6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBookName6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Name of the Book"));
        jPanelHistory.add(jTextFieldBookName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 200, 40));

        jTextFieldBookName7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBookName7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Author of the Book"));
        jPanelHistory.add(jTextFieldBookName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 200, 40));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable4);

        jPanelHistory.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 750, 320));

        jButtonCancelRequest2.setBackground(new java.awt.Color(0, 102, 102));
        jButtonCancelRequest2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonCancelRequest2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelRequest2.setIcon(new javax.swing.ImageIcon("C:\\SLIIT\\LibraryManagementSystem\\src\\View\\Images\\reservebtn.png")); // NOI18N
        jButtonCancelRequest2.setText("Cancel Request");
        jButtonCancelRequest2.setFocusable(false);
        jButtonCancelRequest2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonCancelRequest2.setMargin(new java.awt.Insets(2, 0, 2, 5));
        jPanelHistory.add(jButtonCancelRequest2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 120, 30));

        jTabbedPanelHistory.addTab("Borrowed Book History", jPanelHistory);

        jPanelHsitory.add(jTabbedPanelHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 570));

        jPanelToggle.add(jPanelHsitory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 570));

        jPanelFeedback.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFeedback.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPanelFeedback.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPanelFeedback.setFocusable(false);
        jTabbedPanelFeedback.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanelFeedback1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFeedback1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldISBN5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldISBN5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "ISBN of the Book"));
        jPanelFeedback1.add(jTextFieldISBN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 200, 40));

        jTextFieldBookName8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBookName8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Name of the Book"));
        jPanelFeedback1.add(jTextFieldBookName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 200, 40));

        jTextFieldBookName9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBookName9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Author of the Book"));
        jPanelFeedback1.add(jTextFieldBookName9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 200, 40));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable5);

        jPanelFeedback1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 750, 320));

        jButtonCancelRequest3.setBackground(new java.awt.Color(0, 102, 102));
        jButtonCancelRequest3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonCancelRequest3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelRequest3.setIcon(new javax.swing.ImageIcon("C:\\SLIIT\\LibraryManagementSystem\\src\\View\\Images\\reservebtn.png")); // NOI18N
        jButtonCancelRequest3.setText("Cancel Request");
        jButtonCancelRequest3.setFocusable(false);
        jButtonCancelRequest3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonCancelRequest3.setMargin(new java.awt.Insets(2, 0, 2, 5));
        jPanelFeedback1.add(jButtonCancelRequest3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 120, 30));

        jTabbedPanelFeedback.addTab("Feedbacks of Books", jPanelFeedback1);

        jPanelSubmitFeedback.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSubmitFeedback.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldBookId1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBookId1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Book ID"));
        jPanelSubmitFeedback.add(jTextFieldBookId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 40));

        jTextFieldAvailability1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldAvailability1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Availability"));
        jPanelSubmitFeedback.add(jTextFieldAvailability1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 200, 40));

        jTextFieldReserveISBN1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldReserveISBN1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Book ISBN"));
        jPanelSubmitFeedback.add(jTextFieldReserveISBN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 200, 40));

        jScrollPane7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Description"));

        jTextAreaDescription1.setColumns(20);
        jTextAreaDescription1.setRows(6);
        jScrollPane7.setViewportView(jTextAreaDescription1);

        jPanelSubmitFeedback.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 520, 140));

        jTextFieldAuthor1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldAuthor1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Author Name"));
        jPanelSubmitFeedback.add(jTextFieldAuthor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 200, 40));

        jTextFieldReserveBookName1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldReserveBookName1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Book Name"));
        jPanelSubmitFeedback.add(jTextFieldReserveBookName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 200, 40));

        jButtonConfirmReservation1.setBackground(new java.awt.Color(0, 102, 102));
        jButtonConfirmReservation1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonConfirmReservation1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConfirmReservation1.setIcon(new javax.swing.ImageIcon("C:\\SLIIT\\LibraryManagementSystem\\src\\View\\Images\\reservebtn.png")); // NOI18N
        jButtonConfirmReservation1.setText("Confirm");
        jButtonConfirmReservation1.setFocusable(false);
        jButtonConfirmReservation1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonConfirmReservation1.setMargin(new java.awt.Insets(2, 0, 2, 5));
        jPanelSubmitFeedback.add(jButtonConfirmReservation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 100, 30));

        jTabbedPanelFeedback.addTab("Submit Feedback", jPanelSubmitFeedback);

        jPanelFeedback.add(jTabbedPanelFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 570));

        jPanelToggle.add(jPanelFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 570));

        jPanelSettings.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPanelHistory1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPanelHistory1.setFocusable(false);
        jTabbedPanelHistory1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanelEditProfile.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEditProfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldISBN6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldISBN6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "ISBN of the Book"));
        jPanelEditProfile.add(jTextFieldISBN6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 200, 40));

        jTextFieldBookName10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBookName10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Name of the Book"));
        jPanelEditProfile.add(jTextFieldBookName10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 200, 40));

        jTextFieldBookName11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBookName11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Author of the Book"));
        jPanelEditProfile.add(jTextFieldBookName11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 200, 40));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jTable6);

        jPanelEditProfile.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 750, 320));

        jButtonCancelRequest4.setBackground(new java.awt.Color(0, 102, 102));
        jButtonCancelRequest4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonCancelRequest4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelRequest4.setIcon(new javax.swing.ImageIcon("C:\\SLIIT\\LibraryManagementSystem\\src\\View\\Images\\reservebtn.png")); // NOI18N
        jButtonCancelRequest4.setText("Cancel Request");
        jButtonCancelRequest4.setFocusable(false);
        jButtonCancelRequest4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonCancelRequest4.setMargin(new java.awt.Insets(2, 0, 2, 5));
        jPanelEditProfile.add(jButtonCancelRequest4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 120, 30));

        jTabbedPanelHistory1.addTab("Edit User Profile", jPanelEditProfile);

        jPanelSettings.add(jTabbedPanelHistory1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 570));

        jPanelToggle.add(jPanelSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 570));

        jDesktopPaneLibraryMain.add(jPanelToggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 780, 570));

        getContentPane().add(jDesktopPaneLibraryMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1022, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogout11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogout11MouseEntered
        // TODO add your handling code here:
        jButtonLogout.setBackground(new Color(24, 142, 130));
    }//GEN-LAST:event_jButtonLogout11MouseEntered

    private void jButtonLogout11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogout11MouseExited
        // TODO add your handling code here:
        jButtonLogout.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_jButtonLogout11MouseExited

    private void jButtonReserveBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReserveBookMouseEntered
        // TODO add your handling code here:
        jButtonReserveBook.setBackground(new Color(24, 142, 130));
    }//GEN-LAST:event_jButtonReserveBookMouseEntered

    private void jButtonReserveBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReserveBookMouseExited
        // TODO add your handling code here:
        jButtonReserveBook.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_jButtonReserveBookMouseExited

    private void jButtonRequestedBookListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRequestedBookListMouseEntered
        // TODO add your handling code here:
        jButtonRequestedBookList.setBackground(new Color(24, 142, 130));
    }//GEN-LAST:event_jButtonRequestedBookListMouseEntered

    private void jButtonRequestedBookListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRequestedBookListMouseExited
        // TODO add your handling code here:
        jButtonRequestedBookList.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_jButtonRequestedBookListMouseExited

    private void jButtonPendingReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPendingReturnMouseEntered
        // TODO add your handling code here:
        jButtonPendingReturn.setBackground(new Color(24, 142, 130));
    }//GEN-LAST:event_jButtonPendingReturnMouseEntered

    private void jButtonPendingReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPendingReturnMouseExited
        // TODO add your handling code here:
        jButtonPendingReturn.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_jButtonPendingReturnMouseExited

    private void jButtonHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHistoryMouseEntered
        // TODO add your handling code here:
        jButtonHistory.setBackground(new Color(24, 142, 130));
    }//GEN-LAST:event_jButtonHistoryMouseEntered

    private void jButtonHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHistoryMouseExited
        // TODO add your handling code here:
        jButtonHistory.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_jButtonHistoryMouseExited

    private void jButtonFeedback11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFeedback11MouseEntered
        // TODO add your handling code here:
        jButtonFeedback.setBackground(new Color(24, 142, 130));
    }//GEN-LAST:event_jButtonFeedback11MouseEntered

    private void jButtonFeedback11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFeedback11MouseExited
        // TODO add your handling code here:
        jButtonFeedback.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_jButtonFeedback11MouseExited

    private void jButtonSettings11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSettings11MouseEntered
        // TODO add your handling code here:
        jButtonSettings.setBackground(new Color(24, 142, 130));
    }//GEN-LAST:event_jButtonSettings11MouseEntered

    private void jButtonSettings11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSettings11MouseExited
        // TODO add your handling code here:
        jButtonSettings.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_jButtonSettings11MouseExited

    private void jButtonReserveBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReserveBookActionPerformed
        // TODO add your handling code here:
        togglePanels("ReserveBook");
    }//GEN-LAST:event_jButtonReserveBookActionPerformed

    private void jButtonRequestedBookListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRequestedBookListActionPerformed
        // TODO add your handling code here:
        togglePanels("RequestedList");
    }//GEN-LAST:event_jButtonRequestedBookListActionPerformed

    private void jButtonPendingReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPendingReturnActionPerformed
        // TODO add your handling code here:
        togglePanels("PendingBooks");
    }//GEN-LAST:event_jButtonPendingReturnActionPerformed

    private void jButtonHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHistoryActionPerformed
        // TODO add your handling code here:
        togglePanels("History");
    }//GEN-LAST:event_jButtonHistoryActionPerformed

    private void jButtonFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeedbackActionPerformed
        // TODO add your handling code here:
        togglePanels("Feedbacks");
    }//GEN-LAST:event_jButtonFeedbackActionPerformed

    private void jButtonSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSettingsActionPerformed
        // TODO add your handling code here:
        togglePanels("Settings");
    }//GEN-LAST:event_jButtonSettingsActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed

        int result = JOptionPane.showConfirmDialog(rootPane, "Are you sure want to Logout?", "Confirm Logout", 0);

        if (result == 0) {
            this.dispose();
            SystemLogin login = new SystemLogin();
            login.setVisible(true);
        }
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryMain(USER).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelRequest;
    private javax.swing.JButton jButtonCancelRequest1;
    private javax.swing.JButton jButtonCancelRequest2;
    private javax.swing.JButton jButtonCancelRequest3;
    private javax.swing.JButton jButtonCancelRequest4;
    private javax.swing.JButton jButtonConfirmReservation;
    private javax.swing.JButton jButtonConfirmReservation1;
    private javax.swing.JButton jButtonFeedback;
    private javax.swing.JButton jButtonHistory;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonPendingReturn;
    private javax.swing.JButton jButtonRequestedBookList;
    private javax.swing.JButton jButtonReserveBook;
    private javax.swing.JButton jButtonSearchBook;
    private javax.swing.JButton jButtonSearchBook1;
    private javax.swing.JButton jButtonSettings;
    private javax.swing.JDesktopPane jDesktopPaneLibraryMain;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelWelcomeUser;
    private javax.swing.JLabel jLableTime;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelEditProfile;
    private javax.swing.JPanel jPanelFeedback;
    private javax.swing.JPanel jPanelFeedback1;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelHistory;
    private javax.swing.JPanel jPanelHsitory;
    private javax.swing.JPanel jPanelPending;
    private javax.swing.JPanel jPanelPendingReturn;
    private javax.swing.JPanel jPanelRequestedBookList;
    private javax.swing.JPanel jPanelRequestedList;
    private javax.swing.JPanel jPanelReserveBook;
    private javax.swing.JPanel jPanelReserveBookTab;
    private javax.swing.JPanel jPanelSearchBookTab;
    private javax.swing.JPanel jPanelSettings;
    private javax.swing.JPanel jPanelSubmitFeedback;
    private javax.swing.JPanel jPanelToggle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPanePendingReturn;
    private javax.swing.JTabbedPane jTabbedPaneRequestedList;
    private javax.swing.JTabbedPane jTabbedPaneReserveBook;
    private javax.swing.JTabbedPane jTabbedPanelFeedback;
    private javax.swing.JTabbedPane jTabbedPanelHistory;
    private javax.swing.JTabbedPane jTabbedPanelHistory1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextArea jTextAreaDescription1;
    private javax.swing.JTextField jTextFieldAuthor;
    private javax.swing.JTextField jTextFieldAuthor1;
    private javax.swing.JTextField jTextFieldAvailability;
    private javax.swing.JTextField jTextFieldAvailability1;
    private javax.swing.JTextField jTextFieldBookId;
    private javax.swing.JTextField jTextFieldBookId1;
    private javax.swing.JTextField jTextFieldBookName;
    private javax.swing.JTextField jTextFieldBookName1;
    private javax.swing.JTextField jTextFieldBookName10;
    private javax.swing.JTextField jTextFieldBookName11;
    private javax.swing.JTextField jTextFieldBookName2;
    private javax.swing.JTextField jTextFieldBookName3;
    private javax.swing.JTextField jTextFieldBookName4;
    private javax.swing.JTextField jTextFieldBookName5;
    private javax.swing.JTextField jTextFieldBookName6;
    private javax.swing.JTextField jTextFieldBookName7;
    private javax.swing.JTextField jTextFieldBookName8;
    private javax.swing.JTextField jTextFieldBookName9;
    private javax.swing.JTextField jTextFieldISBN1;
    private javax.swing.JTextField jTextFieldISBN2;
    private javax.swing.JTextField jTextFieldISBN3;
    private javax.swing.JTextField jTextFieldISBN4;
    private javax.swing.JTextField jTextFieldISBN5;
    private javax.swing.JTextField jTextFieldISBN6;
    private javax.swing.JTextField jTextFieldReserveBookName;
    private javax.swing.JTextField jTextFieldReserveBookName1;
    private javax.swing.JTextField jTextFieldReserveISBN;
    private javax.swing.JTextField jTextFieldReserveISBN1;
    // End of variables declaration//GEN-END:variables
}
