/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.SupplierController;
import Model.SupplierModel;
import Util.Utility;
import Validation.Validation;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import static java.lang.Thread.sleep;

/**
 *
 * @author Rushan
 */
public class LibraryManagerMain extends javax.swing.JFrame {

    /**
     * Creates new form LibraryMain
     */
    static String USER;
    static boolean isReserved;

    public LibraryManagerMain(String userName) {
        initComponents();

        USER = userName;
        jLabelWelcomeUser.setText("Welcome " + USER);
        pnlIssueBook.setVisible(false);
        clock();

    }

    private void loadSupplierTable() throws IOException {
        try {
            Utility.loadTable(tblSupplier, "SELECT * FROM SUPPLIERS");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(LibraryManagerMain.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void clearSupplierData() throws IOException {
        try {
            tfCompany.setText("");
            tfAddress.setText("");
            tfMobile.setText("");
            tfSupplerID.setText(SupplierController.autoGenerateSupplierID());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(LibraryManagerMain.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void togglePanels(String buttonName) {
        switch (buttonName) {
            case "ReserveBook":
                pnlIssueBook.setVisible(true);

                break;

            default:
                break;
        }
    }

    public void clock() {
        Thread clock = new Thread() {
            @Override
            public void run() {
                try {
                    for (;;) {
                        Calendar cal = new GregorianCalendar();
                        jLableTime.setText(cal.get(Calendar.HOUR) + ":" + cal.get(Calendar.MINUTE) + ":" + cal.get(Calendar.SECOND) + " / " + cal.get(Calendar.YEAR) + "-" + cal.get(Calendar.MONTH) + "-" + cal.get(Calendar.DATE));
                        sleep(1000);
                    }
                } catch (Exception e) {

                }
            }
        };
        clock.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneLibraryMain = new javax.swing.JDesktopPane();
        jPanelHeader = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelWelcomeUser = new javax.swing.JLabel();
        jLableTime = new javax.swing.JLabel();
        jPanelButtons = new javax.swing.JPanel();
        btnIssueBookTab = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jButtonSettings = new javax.swing.JButton();
        jPanelToggle = new javax.swing.JPanel();
        pnlIssueBook = new javax.swing.JPanel();
        tbIssueBook = new javax.swing.JTabbedPane();
        jPanelSearchBookTab = new javax.swing.JPanel();
        tfSearchSupplier = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        tfSupplerID = new javax.swing.JTextField();
        tfCompany = new javax.swing.JTextField();
        tfAddress = new javax.swing.JTextField();
        tfMobile = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System : Member");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPaneLibraryMain.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPaneLibraryMain.setForeground(new java.awt.Color(255, 255, 255));
        jDesktopPaneLibraryMain.setPreferredSize(new java.awt.Dimension(1022, 710));
        jDesktopPaneLibraryMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHeader.setBackground(new java.awt.Color(0, 102, 102));
        jPanelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/librarylogo.png"))); // NOI18N
        jPanelHeader.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabelWelcomeUser.setForeground(new java.awt.Color(204, 204, 204));
        jLabelWelcomeUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanelHeader.add(jLabelWelcomeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 10, 290, 20));

        jLableTime.setForeground(new java.awt.Color(204, 204, 204));
        jLableTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanelHeader.add(jLableTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 94, 150, 20));

        jDesktopPaneLibraryMain.add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1022, 120));

        jPanelButtons.setBackground(new java.awt.Color(0, 102, 102));
        jPanelButtons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIssueBookTab.setBackground(new java.awt.Color(0, 102, 102));
        btnIssueBookTab.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        btnIssueBookTab.setForeground(new java.awt.Color(255, 255, 255));
        btnIssueBookTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/menuBtn.png"))); // NOI18N
        btnIssueBookTab.setText("SUPPLIER");
        btnIssueBookTab.setFocusPainted(false);
        btnIssueBookTab.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnIssueBookTab.setIconTextGap(5);
        btnIssueBookTab.setMargin(new java.awt.Insets(2, 0, 2, 5));
        btnIssueBookTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIssueBookTabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIssueBookTabMouseExited(evt);
            }
        });
        btnIssueBookTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueBookTabActionPerformed(evt);
            }
        });
        jPanelButtons.add(btnIssueBookTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 40));

        jButtonLogout.setBackground(new java.awt.Color(0, 102, 102));
        jButtonLogout.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/logout.png"))); // NOI18N
        jButtonLogout.setText("LOGOUT");
        jButtonLogout.setFocusPainted(false);
        jButtonLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonLogout.setIconTextGap(5);
        jButtonLogout.setMargin(new java.awt.Insets(2, 0, 2, 5));
        jButtonLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLogout11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLogout11MouseExited(evt);
            }
        });
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        jPanelButtons.add(jButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 190, 40));

        jButtonSettings.setBackground(new java.awt.Color(0, 102, 102));
        jButtonSettings.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jButtonSettings.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/settings.png"))); // NOI18N
        jButtonSettings.setText("SETTINGS");
        jButtonSettings.setFocusPainted(false);
        jButtonSettings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonSettings.setIconTextGap(5);
        jButtonSettings.setMargin(new java.awt.Insets(2, 0, 2, 5));
        jButtonSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSettings11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSettings11MouseExited(evt);
            }
        });
        jButtonSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSettingsActionPerformed(evt);
            }
        });
        jPanelButtons.add(jButtonSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 190, 40));

        jDesktopPaneLibraryMain.add(jPanelButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 210, 570));

        jPanelToggle.setBackground(new java.awt.Color(0, 102, 102));
        jPanelToggle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlIssueBook.setBackground(new java.awt.Color(255, 255, 255));
        pnlIssueBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbIssueBook.setBackground(new java.awt.Color(255, 255, 255));
        tbIssueBook.setFocusable(false);
        tbIssueBook.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbIssueBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbIssueBookMouseClicked(evt);
            }
        });

        jPanelSearchBookTab.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSearchBookTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfSearchSupplier.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfSearchSupplier.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Search"));
        tfSearchSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSearchSupplierKeyReleased(evt);
            }
        });
        jPanelSearchBookTab.add(tfSearchSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, 40));

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSupplier);
        if (tblSupplier.getColumnModel().getColumnCount() > 0) {
            tblSupplier.getColumnModel().getColumn(0).setResizable(false);
            tblSupplier.getColumnModel().getColumn(1).setResizable(false);
            tblSupplier.getColumnModel().getColumn(2).setResizable(false);
            tblSupplier.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanelSearchBookTab.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 750, 170));

        tfSupplerID.setEditable(false);
        tfSupplerID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfSupplerID.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Supplier ID"));
        jPanelSearchBookTab.add(tfSupplerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 200, 40));

        tfCompany.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfCompany.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Company"));
        jPanelSearchBookTab.add(tfCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 200, 40));

        tfAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfAddress.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Address"));
        jPanelSearchBookTab.add(tfAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 200, 40));

        tfMobile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfMobile.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Mobile"));
        jPanelSearchBookTab.add(tfMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 200, 40));

        btnDelete.setBackground(new java.awt.Color(0, 102, 102));
        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/reservebtn.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanelSearchBookTab.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 110, 30));

        btnAdd.setBackground(new java.awt.Color(0, 102, 102));
        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/reservebtn.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setFocusable(false);
        btnAdd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanelSearchBookTab.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 110, 30));

        btnUpdate.setBackground(new java.awt.Color(0, 102, 102));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/reservebtn.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setFocusable(false);
        btnUpdate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanelSearchBookTab.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 110, 30));

        tbIssueBook.addTab("Supplier", jPanelSearchBookTab);

        pnlIssueBook.add(tbIssueBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 570));

        jPanelToggle.add(pnlIssueBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 570));

        jDesktopPaneLibraryMain.add(jPanelToggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 780, 570));

        getContentPane().add(jDesktopPaneLibraryMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1022, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogout11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogout11MouseEntered
        // TODO add your handling code here:
        jButtonLogout.setBackground(new Color(24, 142, 130));
    }//GEN-LAST:event_jButtonLogout11MouseEntered

    private void jButtonLogout11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogout11MouseExited
        // TODO add your handling code here:
        jButtonLogout.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_jButtonLogout11MouseExited

    private void btnIssueBookTabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIssueBookTabMouseEntered
        // TODO add your handling code here:
        btnIssueBookTab.setBackground(new Color(24, 142, 130));
    }//GEN-LAST:event_btnIssueBookTabMouseEntered

    private void btnIssueBookTabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIssueBookTabMouseExited
        // TODO add your handling code here:
        btnIssueBookTab.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btnIssueBookTabMouseExited

    private void jButtonSettings11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSettings11MouseEntered
        // TODO add your handling code here:
        jButtonSettings.setBackground(new Color(24, 142, 130));
    }//GEN-LAST:event_jButtonSettings11MouseEntered

    private void jButtonSettings11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSettings11MouseExited
        // TODO add your handling code here:
        jButtonSettings.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_jButtonSettings11MouseExited

    private void btnIssueBookTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueBookTabActionPerformed
        try {
            togglePanels("ReserveBook");
            loadSupplierTable();
            tfSupplerID.setText(SupplierController.autoGenerateSupplierID());
        } catch (ClassNotFoundException | SQLException | IOException ex) {
            Logger.getLogger(LibraryManagerMain.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnIssueBookTabActionPerformed

    private void jButtonSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSettingsActionPerformed
        // TODO add your handling code here:
        togglePanels("Settings");
    }//GEN-LAST:event_jButtonSettingsActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed

        int result = JOptionPane.showConfirmDialog(rootPane, "Are you sure want to Logout?", "Confirm Logout", 0);

        if (result == 0) {
            this.dispose();
            SystemLogin login = new SystemLogin();
            login.setVisible(true);
        }
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void tbIssueBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbIssueBookMouseClicked
        try {
            // TODO add your handling code here:
            loadSupplierTable();
 
        } catch (IOException ex) {
            Logger.getLogger(LibraryManagerMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbIssueBookMouseClicked

    private void tblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupplierMouseClicked

        int row = tblSupplier.getSelectedRow();

        tfSupplerID.setText(tblSupplier.getValueAt(row, 0).toString());
        tfCompany.setText(tblSupplier.getValueAt(row, 1).toString());
        tfAddress.setText(tblSupplier.getValueAt(row, 2).toString());
        tfMobile.setText(tblSupplier.getValueAt(row, 3).toString());

//        try {
//            //tfIssueBBID.setText(BookController.autoGenerateBorrowedID());
//        } catch (ClassNotFoundException | SQLException ex) {
//            Logger.getLogger(LibraryManagerMain.class.getName()).log(Level.SEVERE, null, ex);
//        }

    }//GEN-LAST:event_tblSupplierMouseClicked

    private void tfSearchSupplierKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchSupplierKeyReleased
        try {
            Utility.filter(tblSupplier, tfSearchSupplier.getText());
        } catch (PatternSyntaxException ex) {

        }

    }//GEN-LAST:event_tfSearchSupplierKeyReleased

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (!tfSupplerID.getText().isEmpty()) {
            try {
                if (SupplierController.deleteSupplier(tfSupplerID.getText())) {
                    JOptionPane.showMessageDialog(rootPane, "Successfully deleted", "Deleted!", JOptionPane.INFORMATION_MESSAGE);
                    loadSupplierTable();
                    clearSupplierData();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Invalid Supplier Id", "Error!", JOptionPane.ERROR_MESSAGE);

                }
            } catch (ClassNotFoundException | SQLException | IOException ex) {
                Logger.getLogger(LibraryManagerMain.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Supplier ID Can't be empty", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        if (!tfCompany.getText().isEmpty()) {
            if (!tfAddress.getText().isEmpty()) {
                if (Validation.isNumbers(tfMobile.getText()) && tfMobile.getText().length() == 10) {
                    try {
                        if (SupplierController.addSupplier(new SupplierModel(tfSupplerID.getText(), tfCompany.getText(), tfAddress.getText(), Integer.parseInt(tfMobile.getText())))) {
                            JOptionPane.showMessageDialog(rootPane, "Successfully added", "Success!", JOptionPane.INFORMATION_MESSAGE);
                            loadSupplierTable();
                            clearSupplierData();
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Error occured while inserting", "Error!", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (ClassNotFoundException | SQLException | IOException ex) {
                        Logger.getLogger(LibraryManagerMain.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Invalid phone number", "Error!", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Company Name can't be empty", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (!tfSupplerID.getText().isEmpty()) {
            if (!tfCompany.getText().isEmpty()) {
                if (!tfAddress.getText().isEmpty()) {
                    if (Validation.isNumbers(tfMobile.getText()) && (tfMobile.getText().length() == 10 || tfMobile.getText().length() == 9)) {
                        try {
                            if (SupplierController.editSupplier(new SupplierModel(tfSupplerID.getText(), tfCompany.getText(), tfAddress.getText(), Integer.parseInt(tfMobile.getText())))) {
                                JOptionPane.showMessageDialog(rootPane, "Successfully updated", "Success!", JOptionPane.INFORMATION_MESSAGE);
                                loadSupplierTable();
                                clearSupplierData();
                            } else {
                                JOptionPane.showMessageDialog(rootPane, "Invalid Supplier id", "Error!", JOptionPane.ERROR_MESSAGE);
                            }
                        } catch (ClassNotFoundException | SQLException | IOException ex) {
                            Logger.getLogger(LibraryManagerMain.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Invalid phone number", "Error!", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Invalid Address", "Error!", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Company Name can't be empty", "Error!", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Supplier ID Can't be empty", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryManagerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new LibraryManagerMain(USER).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnIssueBookTab;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonSettings;
    private javax.swing.JDesktopPane jDesktopPaneLibraryMain;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelWelcomeUser;
    private javax.swing.JLabel jLableTime;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelSearchBookTab;
    private javax.swing.JPanel jPanelToggle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlIssueBook;
    private javax.swing.JTabbedPane tbIssueBook;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfCompany;
    private javax.swing.JTextField tfMobile;
    private javax.swing.JTextField tfSearchSupplier;
    private javax.swing.JTextField tfSupplerID;
    // End of variables declaration//GEN-END:variables
}
